Support cosmetic filterlists
duckduckgo/autoconsent pull request #466
Opened 2024-07-24 10:45 UTC by muodov

2024-10-07 13:54 UTC, muodov commented on lib/web.ts
> +    // this may be a false positive: sometimes filters hide unrelated elements that are not cookie pop-ups
note that we still need to do this check to know if we should report to the background script

2024-10-07 13:55 UTC, muodov commented on lib/web.ts
> +    }
just a cleanup

2024-10-07 13:59 UTC, muodov commented on lib/utils.ts
> +    enableFilterList: false,
filterlist should be explicitly enabled by the browser

2024-10-24 12:08 UTC, sammacbeth requested changes
Looks good - just a couple of minor changes I think would improve it.

2024-10-24 12:08 UTC, sammacbeth commented on rules/filterlists/overrides.txt
> +duckduckgo.com#@#li[data-layout="ad"]
This one can be removed now, right?

2024-11-06 12:59 UTC, muodov commented on package.json
> +    "@cliqz/adblocker-content": "^1.33.1",
thanks for flagging, I updated it

2024-11-06 13:00 UTC, muodov commented on lib/types.ts
> +  autoconsent?: AutoConsentCMPRule[];
you're right, I made it required

2024-11-06 13:00 UTC, muodov commented on package.json
> +    "fetch-easylist": "rm -f rules/filterlists/easylist_cookie_* && wget --directory-prefix=rules/filterlists/ https://raw.githubusercontent.com/easylist/easylist/refs/heads/master/easylist_cookie/ea
made changes as discussed: we're now tracking the resulting filterlist in git

2024-11-06 13:00 UTC, muodov commented on rules/filterlists/overrides.txt
> +duckduckgo.com#@#li[data-layout="ad"]
yep

2024-11-07 10:32 UTC, merged